export type AttendanceStatus = "Present" | "Absent" | "Leave";

export interface AttendanceRecord {
  classNumber: number;
  date: string;
  status: AttendanceStatus;
}

export interface AttendanceSummary {
  totalClasses: number;
  present: number;
  leave: number;
  absent: number;
}

export interface MonthlyAttendance extends AttendanceSummary {
  month: string;
  records: AttendanceRecord[];
}

export const attendanceMonths: string[] = [
  "Oct 2025",
  "Nov 2025",
  "Dec 2025",
  "Jan 2026",
  "Feb 2026",
  "Mar 2026",
  "Apr 2026",
  "May 2026",
  "Jun 2026",
  "Jul 2026",
  "Aug 2026",
  "Sep 2026",
];

export const attendanceByMonth: Record<string, MonthlyAttendance> = {
  "Oct 2025": {
    month: "Oct 2025",
    totalClasses: 14,
    present: 13,
    leave: 0,
    absent: 1,
    records: [
      { classNumber: 1, date: "Wed, Oct 1, 2025", status: "Present" },
      { classNumber: 2, date: "Fri, Oct 3, 2025", status: "Absent" },
      { classNumber: 3, date: "Mon, Oct 6, 2025", status: "Present" },
      { classNumber: 4, date: "Wed, Oct 8, 2025", status: "Present" },
      { classNumber: 5, date: "Fri, Oct 10, 2025", status: "Present" },
      { classNumber: 6, date: "Mon, Oct 13, 2025", status: "Present" },
      { classNumber: 7, date: "Wed, Oct 15, 2025", status: "Present" },
      { classNumber: 8, date: "Fri, Oct 17, 2025", status: "Present" },
      { classNumber: 9, date: "Mon, Oct 20, 2025", status: "Present" },
      { classNumber: 10, date: "Wed, Oct 22, 2025", status: "Present" },
      { classNumber: 11, date: "Fri, Oct 24, 2025", status: "Present" },
      { classNumber: 12, date: "Mon, Oct 27, 2025", status: "Present" },
      { classNumber: 13, date: "Wed, Oct 29, 2025", status: "Present" },
      { classNumber: 14, date: "Fri, Oct 31, 2025", status: "Present" },
    ],
  },
  "Nov 2025": {
    month: "Nov 2025",
    totalClasses: 12,
    present: 9,
    leave: 1,
    absent: 2,
    records: [
      { classNumber: 1, date: "Mon, Nov 3, 2025", status: "Present" },
      { classNumber: 2, date: "Wed, Nov 5, 2025", status: "Absent" },
      { classNumber: 3, date: "Fri, Nov 7, 2025", status: "Leave" },
      { classNumber: 4, date: "Mon, Nov 10, 2025", status: "Present" },
      { classNumber: 5, date: "Wed, Nov 12, 2025", status: "Present" },
      { classNumber: 6, date: "Fri, Nov 14, 2025", status: "Present" },
      { classNumber: 7, date: "Mon, Nov 17, 2025", status: "Present" },
      { classNumber: 8, date: "Wed, Nov 19, 2025", status: "Absent" },
      { classNumber: 9, date: "Fri, Nov 21, 2025", status: "Present" },
      { classNumber: 10, date: "Mon, Nov 24, 2025", status: "Present" },
      { classNumber: 11, date: "Wed, Nov 26, 2025", status: "Present" },
      { classNumber: 12, date: "Fri, Nov 28, 2025", status: "Present" },
    ],
  },
  "Dec 2025": {
    month: "Dec 2025",
    totalClasses: 14,
    present: 9,
    leave: 0,
    absent: 5,
    records: [
      { classNumber: 1, date: "Mon, Dec 1, 2025", status: "Present" },
      { classNumber: 2, date: "Wed, Dec 3, 2025", status: "Absent" },
      { classNumber: 3, date: "Fri, Dec 5, 2025", status: "Present" },
      { classNumber: 4, date: "Mon, Dec 8, 2025", status: "Absent" },
      { classNumber: 5, date: "Wed, Dec 10, 2025", status: "Present" },
      { classNumber: 6, date: "Fri, Dec 12, 2025", status: "Absent" },
      { classNumber: 7, date: "Mon, Dec 15, 2025", status: "Present" },
      { classNumber: 8, date: "Wed, Dec 17, 2025", status: "Absent" },
      { classNumber: 9, date: "Fri, Dec 19, 2025", status: "Present" },
      { classNumber: 10, date: "Mon, Dec 22, 2025", status: "Absent" },
      { classNumber: 11, date: "Wed, Dec 24, 2025", status: "Present" },
      { classNumber: 12, date: "Fri, Dec 26, 2025", status: "Present" },
      { classNumber: 13, date: "Mon, Dec 29, 2025", status: "Present" },
      { classNumber: 14, date: "Wed, Dec 31, 2025", status: "Present" },
    ],
  },
  "Jan 2026": {
    month: "Jan 2026",
    totalClasses: 13,
    present: 11,
    leave: 1,
    absent: 1,
    records: [
      { classNumber: 1, date: "Fri, Jan 2, 2026", status: "Present" },
      { classNumber: 2, date: "Mon, Jan 5, 2026", status: "Absent" },
      { classNumber: 3, date: "Wed, Jan 7, 2026", status: "Leave" },
      { classNumber: 4, date: "Fri, Jan 9, 2026", status: "Present" },
      { classNumber: 5, date: "Mon, Jan 12, 2026", status: "Present" },
      { classNumber: 6, date: "Wed, Jan 14, 2026", status: "Present" },
      { classNumber: 7, date: "Fri, Jan 16, 2026", status: "Present" },
      { classNumber: 8, date: "Mon, Jan 19, 2026", status: "Present" },
      { classNumber: 9, date: "Wed, Jan 21, 2026", status: "Present" },
      { classNumber: 10, date: "Fri, Jan 23, 2026", status: "Present" },
      { classNumber: 11, date: "Mon, Jan 26, 2026", status: "Present" },
      { classNumber: 12, date: "Wed, Jan 28, 2026", status: "Present" },
      { classNumber: 13, date: "Fri, Jan 30, 2026", status: "Present" },
    ],
  },
  "Feb 2026": {
    month: "Feb 2026",
    totalClasses: 12,
    present: 11,
    leave: 0,
    absent: 1,
    records: [
      { classNumber: 1, date: "Mon, Feb 2, 2026", status: "Present" },
      { classNumber: 2, date: "Wed, Feb 4, 2026", status: "Absent" },
      { classNumber: 3, date: "Fri, Feb 6, 2026", status: "Present" },
      { classNumber: 4, date: "Mon, Feb 9, 2026", status: "Present" },
      { classNumber: 5, date: "Wed, Feb 11, 2026", status: "Present" },
      { classNumber: 6, date: "Fri, Feb 13, 2026", status: "Present" },
      { classNumber: 7, date: "Mon, Feb 16, 2026", status: "Present" },
      { classNumber: 8, date: "Wed, Feb 18, 2026", status: "Present" },
      { classNumber: 9, date: "Fri, Feb 20, 2026", status: "Present" },
      { classNumber: 10, date: "Mon, Feb 23, 2026", status: "Present" },
      { classNumber: 11, date: "Wed, Feb 25, 2026", status: "Present" },
      { classNumber: 12, date: "Fri, Feb 27, 2026", status: "Present" },
    ],
  },
  "Mar 2026": {
    month: "Mar 2026",
    totalClasses: 13,
    present: 10,
    leave: 1,
    absent: 2,
    records: [
      { classNumber: 1, date: "Mon, Mar 2, 2026", status: "Present" },
      { classNumber: 2, date: "Wed, Mar 4, 2026", status: "Absent" },
      { classNumber: 3, date: "Fri, Mar 6, 2026", status: "Leave" },
      { classNumber: 4, date: "Mon, Mar 9, 2026", status: "Present" },
      { classNumber: 5, date: "Wed, Mar 11, 2026", status: "Present" },
      { classNumber: 6, date: "Fri, Mar 13, 2026", status: "Present" },
      { classNumber: 7, date: "Mon, Mar 16, 2026", status: "Present" },
      { classNumber: 8, date: "Wed, Mar 18, 2026", status: "Present" },
      { classNumber: 9, date: "Fri, Mar 20, 2026", status: "Absent" },
      { classNumber: 10, date: "Mon, Mar 23, 2026", status: "Present" },
      { classNumber: 11, date: "Wed, Mar 25, 2026", status: "Present" },
      { classNumber: 12, date: "Fri, Mar 27, 2026", status: "Present" },
      { classNumber: 13, date: "Mon, Mar 30, 2026", status: "Present" },
    ],
  },
  "Apr 2026": {
    month: "Apr 2026",
    totalClasses: 13,
    present: 12,
    leave: 0,
    absent: 1,
    records: [
      { classNumber: 1, date: "Wed, Apr 1, 2026", status: "Present" },
      { classNumber: 2, date: "Fri, Apr 3, 2026", status: "Absent" },
      { classNumber: 3, date: "Mon, Apr 6, 2026", status: "Present" },
      { classNumber: 4, date: "Wed, Apr 8, 2026", status: "Present" },
      { classNumber: 5, date: "Fri, Apr 10, 2026", status: "Present" },
      { classNumber: 6, date: "Mon, Apr 13, 2026", status: "Present" },
      { classNumber: 7, date: "Wed, Apr 15, 2026", status: "Present" },
      { classNumber: 8, date: "Fri, Apr 17, 2026", status: "Present" },
      { classNumber: 9, date: "Mon, Apr 20, 2026", status: "Present" },
      { classNumber: 10, date: "Wed, Apr 22, 2026", status: "Present" },
      { classNumber: 11, date: "Fri, Apr 24, 2026", status: "Present" },
      { classNumber: 12, date: "Mon, Apr 27, 2026", status: "Present" },
      { classNumber: 13, date: "Wed, Apr 29, 2026", status: "Present" },
    ],
  },
  "May 2026": {
    month: "May 2026",
    totalClasses: 13,
    present: 8,
    leave: 1,
    absent: 4,
    records: [
      { classNumber: 1, date: "Fri, May 1, 2026", status: "Present" },
      { classNumber: 2, date: "Mon, May 4, 2026", status: "Absent" },
      { classNumber: 3, date: "Wed, May 6, 2026", status: "Leave" },
      { classNumber: 4, date: "Fri, May 8, 2026", status: "Present" },
      { classNumber: 5, date: "Mon, May 11, 2026", status: "Present" },
      { classNumber: 6, date: "Wed, May 13, 2026", status: "Absent" },
      { classNumber: 7, date: "Fri, May 15, 2026", status: "Present" },
      { classNumber: 8, date: "Mon, May 18, 2026", status: "Present" },
      { classNumber: 9, date: "Wed, May 20, 2026", status: "Absent" },
      { classNumber: 10, date: "Fri, May 22, 2026", status: "Present" },
      { classNumber: 11, date: "Mon, May 25, 2026", status: "Present" },
      { classNumber: 12, date: "Wed, May 27, 2026", status: "Absent" },
      { classNumber: 13, date: "Fri, May 29, 2026", status: "Present" },
    ],
  },
  "Jun 2026": {
    month: "Jun 2026",
    totalClasses: 13,
    present: 11,
    leave: 0,
    absent: 2,
    records: [
      { classNumber: 1, date: "Mon, Jun 1, 2026", status: "Present" },
      { classNumber: 2, date: "Wed, Jun 3, 2026", status: "Absent" },
      { classNumber: 3, date: "Fri, Jun 5, 2026", status: "Present" },
      { classNumber: 4, date: "Mon, Jun 8, 2026", status: "Present" },
      { classNumber: 5, date: "Wed, Jun 10, 2026", status: "Present" },
      { classNumber: 6, date: "Fri, Jun 12, 2026", status: "Present" },
      { classNumber: 7, date: "Mon, Jun 15, 2026", status: "Present" },
      { classNumber: 8, date: "Wed, Jun 17, 2026", status: "Absent" },
      { classNumber: 9, date: "Fri, Jun 19, 2026", status: "Present" },
      { classNumber: 10, date: "Mon, Jun 22, 2026", status: "Present" },
      { classNumber: 11, date: "Wed, Jun 24, 2026", status: "Present" },
      { classNumber: 12, date: "Fri, Jun 26, 2026", status: "Present" },
      { classNumber: 13, date: "Mon, Jun 29, 2026", status: "Present" },
    ],
  },
  "Jul 2026": {
    month: "Jul 2026",
    totalClasses: 14,
    present: 13,
    leave: 0,
    absent: 1,
    records: [
      { classNumber: 1, date: "Wed, Jul 1, 2026", status: "Present" },
      { classNumber: 2, date: "Fri, Jul 3, 2026", status: "Absent" },
      { classNumber: 3, date: "Mon, Jul 6, 2026", status: "Present" },
      { classNumber: 4, date: "Wed, Jul 8, 2026", status: "Present" },
      { classNumber: 5, date: "Fri, Jul 10, 2026", status: "Present" },
      { classNumber: 6, date: "Mon, Jul 13, 2026", status: "Present" },
      { classNumber: 7, date: "Wed, Jul 15, 2026", status: "Present" },
      { classNumber: 8, date: "Fri, Jul 17, 2026", status: "Present" },
      { classNumber: 9, date: "Mon, Jul 20, 2026", status: "Present" },
      { classNumber: 10, date: "Wed, Jul 22, 2026", status: "Present" },
      { classNumber: 11, date: "Fri, Jul 24, 2026", status: "Present" },
      { classNumber: 12, date: "Mon, Jul 27, 2026", status: "Present" },
      { classNumber: 13, date: "Wed, Jul 29, 2026", status: "Present" },
      { classNumber: 14, date: "Fri, Jul 31, 2026", status: "Present" },
    ],
  },
  "Aug 2026": {
    month: "Aug 2026",
    totalClasses: 13,
    present: 10,
    leave: 1,
    absent: 2,
    records: [
      { classNumber: 1, date: "Mon, Aug 3, 2026", status: "Present" },
      { classNumber: 2, date: "Wed, Aug 5, 2026", status: "Absent" },
      { classNumber: 3, date: "Fri, Aug 7, 2026", status: "Leave" },
      { classNumber: 4, date: "Mon, Aug 10, 2026", status: "Present" },
      { classNumber: 5, date: "Wed, Aug 12, 2026", status: "Present" },
      { classNumber: 6, date: "Fri, Aug 14, 2026", status: "Present" },
      { classNumber: 7, date: "Mon, Aug 17, 2026", status: "Present" },
      { classNumber: 8, date: "Wed, Aug 19, 2026", status: "Present" },
      { classNumber: 9, date: "Fri, Aug 21, 2026", status: "Absent" },
      { classNumber: 10, date: "Mon, Aug 24, 2026", status: "Present" },
      { classNumber: 11, date: "Wed, Aug 26, 2026", status: "Present" },
      { classNumber: 12, date: "Fri, Aug 28, 2026", status: "Present" },
      { classNumber: 13, date: "Mon, Aug 31, 2026", status: "Present" },
    ],
  },
  "Sep 2026": {
    month: "Sep 2026",
    totalClasses: 13,
    present: 11,
    leave: 1,
    absent: 1,
    records: [
      { classNumber: 1, date: "Wed, Sep 2, 2026", status: "Present" },
      { classNumber: 2, date: "Fri, Sep 4, 2026", status: "Absent" },
      { classNumber: 3, date: "Mon, Sep 7, 2026", status: "Leave" },
      { classNumber: 4, date: "Wed, Sep 9, 2026", status: "Present" },
      { classNumber: 5, date: "Fri, Sep 11, 2026", status: "Present" },
      { classNumber: 6, date: "Mon, Sep 14, 2026", status: "Present" },
      { classNumber: 7, date: "Wed, Sep 16, 2026", status: "Present" },
      { classNumber: 8, date: "Fri, Sep 18, 2026", status: "Present" },
      { classNumber: 9, date: "Mon, Sep 21, 2026", status: "Present" },
      { classNumber: 10, date: "Wed, Sep 23, 2026", status: "Present" },
      { classNumber: 11, date: "Fri, Sep 25, 2026", status: "Present" },
      { classNumber: 12, date: "Mon, Sep 28, 2026", status: "Present" },
      { classNumber: 13, date: "Wed, Sep 30, 2026", status: "Present" },
    ],
  },
};

export const defaultAttendanceMonth = "Sep 2026";

// Course-wide totals to date (sum of every month above) — this is what the
// stat cards and the overview card show. The month dropdown only changes
// which month's classes appear in the table below; it never changes these.
export const overallAttendance: AttendanceSummary = Object.values(attendanceByMonth).reduce(
  (acc, m) => ({
    totalClasses: acc.totalClasses + m.totalClasses,
    present: acc.present + m.present,
    leave: acc.leave + m.leave,
    absent: acc.absent + m.absent,
  }),
  { totalClasses: 0, present: 0, leave: 0, absent: 0 },
);